### ISSUE TITLE
[Bug] Branch can only read data in latest schema

### ISSUE THREAD

**Issue by gmdfalk** [apache/paimon#4407]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.0-SNAPSHOT

### Compute Engine

Flink

### Minimal reproduce step

1. Create table with schema version 1
2. Insert some values
3. Alter table to create schema version 2 (but don't insert any new values)
4. Create tag & branch
5. Select * from branch 

The select job will fail because it only has schema version 2 but will try to read schema version 1.
Example stacktrace: https://gist.github.com/gmdfalk/802eb18c912a4d85e17f206820a0c55a

### What doesn't meet your expectations?

I expect the branch to be able to read any data, not just in the latest schema.
The branch only knows schema 2 and cannot read entries written in schema 1.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
@gmdfalk Thanks for your report! I would like to update with more detailed reproduction steps:

1. 

```
CREATE TABLE T (
 pt INT,
 k INT,
 v STRING,
 PRIMARY KEY (pt, k) NOT ENFORCED
 ) PARTITIONED BY (pt) WITH (
 'bucket' = '2'
)
```

2. `INSERT INTO T VALUES (1, 10, 'apple'), (1, 20, 'banana')`
3. `ALTER TABLE `T` ADD (v2 INT)`
4. `INSERT INTO T VALUES  (2, 10, 'cat', 2), (2, 20, 'dog', 2)`
5.  `CALL sys.create_tag('default.T', 'tag1', 2)`
6. `CALL sys.create_branch('default.T', 'test', 'tag1')`
7. `SELECT * FROM T$branch_test`

The reason for this bug is that only the tag or latest schema is copied when creating a branch.
