### ISSUE TITLE
[Bug] Cannot run program "zip" exception reported when Windows system compiles

### ISSUE THREAD

**Issue by s7monk** [apache/paimon#941]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

Flink

### Minimal reproduce step

Because the paimon-e2e-tests module adds the <executable>zip</executable> configuration.After I update the code, compile with Windows system and report Cannot run program "zip" exception.

I put the zip.exe file in the bin directory of jdk, the problem is solved。

![微信截图_20230419082919](https://user-images.githubusercontent.com/34889415/232935488-c0aa9aed-3aa7-482c-84b5-654d88fe207f.png)

### What doesn't meet your expectations?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
You may encounter a "Cannot run program 'zip'" exception. This is because Windows does not have the zip command installed by default, so Maven cannot find the executable.

To fix this, you need to have the zip command installed on your Windows system. You can download GNU zip for Windows from http://gnuwin32.sourceforge.net/packages/zip.htm, then add zip.exe to your system PATH environment variable.

**Comment by JingsongLi** [comment]
We can use jar instead of zip.

**Comment by q977734161** [comment]
I am willing to try this ticket, counld you assign it to me！

**Comment by tsreaper** [comment]
@q977734161 thanks for your interest in contributing! Before assigning you to this ticket, could you briefly explain how are you going to fix this issue? Which command are you going to use instead of `zip -d`?

**Comment by lianghuan-xatu** [comment]
> @q977734161 thanks for your interest in contributing! Before assigning you to this ticket, could you briefly explain how are you going to fix this issue? Which command are you going to use instead of `zip -d`?

please assign it  to me, and i will use command "jar cvf test.jar mydir/* --exclude dir/unwanted_directory/ --exclude mydir/unwanted_file" to instead of command 'zip -d'. Thx!

**Comment by q977734161** [comment]
@tsreaper still use **zip -d**, but i am going to use  **maven-antrun-plugin** instead of **exec-maven-plugin** ,At the same time, add the judgment script ,If the system is Windows , use **certutil** to download **zip. exe**, and then use the command **zip - d**; Otherwise, execute **zip - d** directly.
`<contains string="${os.name}" substring="Mac"/>
                                    <then>
                                        <exec executable="certutil">
                                            <arg line="-urlcache -split -f http://stahlworks.com/dev/zip.exe /tmp/paimon-e2e-tests-jars/zip.exe"></arg>
                                        </exec>
                                        <exec executable="/tmp/paimon-e2e-tests-jars/zip.exe">
                                            <arg line=" -d /tmp/paimon-e2e-tests-jars/bundled-hadoop.jar org/apache/commons/cli/CommandLine.class"></arg>
                                        </exec>
                                    </then>
                                    <else>
                                        <exec executable="zip">
                                            <arg line=" -d /tmp/paimon-e2e-tests-jars/bundled-hadoop.jar org/apache/commons/cli/CommandLine.class"></arg>
                                        </exec>
                                    </else>`

**Comment by tsreaper** [comment]
Hi @lianghuan-xatu @q977734161 , thanks for your solutions. In my opinion, using `jar` is a better solution than downloading `zip.exe`, because Paimon is a Java project and user must have jdk to build it. @lianghuan-xatu please submit a pull request as soon as possible.

**Comment by q977734161** [comment]
I think using **jar** is not very convenient either. We need to decompress the jar package , delete the class, and then package it. As **jar** do not support decompressing to the specified directory, Many commands are needed in the process 
 and different operating system commands are incompatible. It is necessary to write different scripts for each operating system.

**Comment by tsreaper** [comment]
Hi @q977734161 , thanks for your feedback.

You mentioned that for our current `jar` solution, it might be "necessary to write different scripts for each operating system". However your `certutil` solution is also exclusive to Windows as we don't have `cerutil` on Mac or Linux. I guess writing scripts for different operating system is not a strong downside.

Also, what I like the `jar` solution most is that it uses existing applications in the user's environment, rather than downloading a new one.

**Comment by q977734161** [comment]
Got it, I understand what your think now

**Comment by dbac** [comment]
Why does the bug close without fixing it?
@tsreaper @JingsongLi

**Comment by dbac** [comment]
http://stahlworks.com/dev/zip.exe

I found that download this file to windows system32 will do

**Comment by tsreaper** [comment]
Hi @dbac , we currently does not guarantee the compilation and usage of Paimon on Windows.
